spring:
  datasource:
    hikari:
      maximum-pool-size: 4
      minimum-idle: 1
      connection-timeout: 5000
      idle-timeout: 60000
      max-lifetime: 240000
      keepalive-time: 30000
      leak-detection-threshold: 20000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update   # <-- Use 'update' for now since Hibernate is being used
    properties:
      jakarta.persistence.query.timeout: 30000
  transaction:
    default-timeout: 30s

